import assert from 'node:assert/strict';
import handler from './src/index.js';
const env={ALLOWED_ORIGIN:'http://localhost:5173',GEMINI_API_KEY:'fake',GEMINI_MODEL:'gemini-3.5-flash-lite'};
const originalFetch=globalThis.fetch;
let calls=0;
let lastTutorPayload;
let modelPhase='Step 2';
const question={prompt:'Which estimate follows from the Cauchy condition?',options:['$d(x_n,x_m)<\\varepsilon$ for all large $n,m$','$d(x_n,x_m)>\\varepsilon$','$x_n=x_m$','$x_n$ is bounded only','$x_n$ is constant'],correctAnswer:'A',skill:'Cauchy condition',difficulty:'standard',diagram:{type:'sequence',caption:'Later terms approach the limit.',labels:[]}};
globalThis.fetch=async (_url,opts)=>{
 calls++;
 assert.equal(opts.headers['x-goog-api-key'],'fake');
 const request=JSON.parse(opts.body);
 assert.doesNotMatch(request.systemInstruction.parts[0].text,/Proofwise|V2/i,'internal product/framework labels must not reach the model');
 lastTutorPayload=JSON.parse(request.contents[0].parts[0].text);
 if(lastTutorPayload.problemText==='') assert.deepEqual(request.contents[0].parts[1].inlineData,{mimeType:'image/png',data:'AQID'});
 
 const result={problem:'Image problem transcription',feedback:'Check how the definition quantifies over both indices.',explanation:'The Cauchy condition controls every pair of sufficiently late terms.',isCorrect:true,learningPlan:{focus:'Cauchy condition',nextMove:'Use the Cauchy estimate in the original proof.'},uniqueCorrectChoice:true,correctAnswerRationale:'The displayed choice is the only one matching the definition.',diagnosedSkill:'Cauchy condition',phase:modelPhase,difficulty:'standard',nextQuestion:question};
 return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(result)}]}}]}),{headers:{'Content-Type':'application/json'}});
};
const req=(path,origin,body)=>new Request('https://example.workers.dev'+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
try{
 const blocked=await handler.fetch(req('/tutor','https://evil.example',{theorem:'Test'}),env);
 assert.equal(blocked.status,403);
 const start=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18'}),env);
 assert.equal(start.status,200);
 const started=await start.json();
 assert.equal(started.nextQuestion.options.length,5);
 assert.equal(started.nextQuestion.correctAnswer,'A');
 assert.equal(started.answerCorrect,null);
 assert.equal(lastTutorPayload.difficulty,'adaptive','pace is inferred from learner performance');
 const imageStart=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'',image:{mimeType:'image/png',data:'AQID'}}),env);
 assert.equal(imageStart.status,200);
 const imageResult=await imageStart.json();
 assert.equal(imageResult.problem,'Image problem transcription','image text should be transcribed before starting');
 assert.equal(lastTutorPayload.problemText,'');
 const badImage=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'',image:{mimeType:'image/svg+xml',data:'PHN2Zy8+'}}),env);
 assert.equal(badImage.status,400,'unsupported images must be rejected');
 const wrong=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18',phase:'Phase 2',currentQuestion:question,answer:'B',reasoning:'I thought only consecutive terms matter.',diagnosticsCount:0}),env);
 const evaluated=await wrong.json();
 assert.equal(lastTutorPayload.answerCorrect,false);
 assert.equal(lastTutorPayload.learnerExplanation,'I thought only consecutive terms matter.');
 assert.equal(evaluated.answerCorrect,false);
 assert.equal(evaluated.isCorrect,false,'server answer key must override contradictory model verdict');
 assert.equal(evaluated.phase,'Step 2','the tutor may advance when performance supports it');
 assert.equal('awaitingSillyMistake' in evaluated,false);
 modelPhase='Step 1';
 const cap=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18',stage:'diagnostic',phase:'Step 1',currentQuestion:question,answer:'A',diagnosticsCount:9,learnerFeedback:{tags:['An example','A hint'],note:'Show how this helps the original proof.'}}),env);
 const capped=await cap.json();
 assert.equal(capped.diagnosticsCount,10);
 assert.equal(capped.stage,'learning');
 assert.equal(capped.phase,'Step 2');
 assert.equal(lastTutorPayload.stage,'learning','the tenth answer must request learning, never an eleventh diagnostic');
 assert.deepEqual(lastTutorPayload.learnerFeedback.tags,['An example','A hint']);
 assert.equal(lastTutorPayload.learnerFeedback.note,'Show how this helps the original proof.');
 assert.ok(capped.learningPlan.nextMove);
 const learning=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18',stage:'learning',phase:'Step 2',currentQuestion:question,answer:'A',diagnosticsCount:10}),env);
 const learned=await learning.json();
 assert.equal(learned.diagnosticsCount,10,'learning answers never increase diagnostic count');
 assert.equal(learned.stage,'learning');
 modelPhase='Step 3';
 const proof=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18',stage:'learning',currentQuestion:question,answer:'A',diagnosticsCount:10}),env);
 assert.equal((await proof.json()).stage,'proof','targeted learning can advance into proof reconstruction');
 modelPhase='Step 2';
 const oversizedCount=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'Lemma 3.18',stage:'diagnostic',diagnosticsCount:100}),env);
 assert.equal((await oversizedCount.json()).diagnosticsCount,10);
 const oversized=await handler.fetch(req('/tutor','http://localhost:5173',{theorem:'x'.repeat(5_800_001)}),env);
 assert.equal(oversized.status,413,'actual request bodies are capped even without Content-Length');
 const health=await handler.fetch(new Request('https://example.workers.dev/health'),env);
 assert.equal(health.status,200);
 console.log('PASS: disallowed origin blocked');
 console.log('PASS: Gemini structured question generation');
 console.log('PASS: server-side answer grading overrides contradictory model output');
 console.log('PASS: optional reasoning and multi-select learner feedback reach the tutor');
 console.log('PASS: hard diagnostic cap, transition plan, and learning-stage counts');
 console.log('PASS: image upload is validated and forwarded for transcription');
 console.log('PASS: request-size cap without Content-Length');
 console.log('PASS: health endpoint');
}finally{globalThis.fetch=originalFetch;}
