import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {InlineMath,BlockMath} from 'react-katex';
import {BookOpen,Brain,ChevronRight,Check,RotateCcw,Send,ShieldCheck,Sparkles,BarChart3,Settings2,AlertCircle,Menu,X,ArrowRight,MessageSquareText} from 'lucide-react';
import 'katex/dist/katex.min.css';
import './styles.css';

const DEFAULT_THEOREM='Lemma 3.18: Let (x_n) be a Cauchy sequence in a metric space (X,d). If (x_n) has a subsequence (x_{n_k}) converging to x ∈ X, prove that x_n → x.';
const API_URL=(import.meta.env.VITE_API_URL||'https://proofwise-api.irtiza-proofwise.workers.dev').replace(/\/$/,'');
const STORAGE='proofwise-v2-state-1';
const phases=[['0','Orientation'],['1','Prerequisites'],['2','Diagnostic'],['3','Mastery training'],['4','Proof reconstruction'],['5','Solution unlock'],['6','Repetition']];
function MathText({text=''}){const parts=String(text).split(/(\$\$[\s\S]+?\$\$|\$[^$\n]+\$)/g);return <>{parts.map((part,i)=>{try{if(part.startsWith('$$')&&part.endsWith('$$'))return <BlockMath key={i} math={part.slice(2,-2)}/>;if(part.startsWith('$')&&part.endsWith('$'))return <InlineMath key={i} math={part.slice(1,-1)}/>;}catch{}return <React.Fragment key={i}>{part}</React.Fragment>;})}</>}
function saved(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}}
function App(){const [state,setState]=useState(saved);const [theorem,setTheorem]=useState(state.theorem||DEFAULT_THEOREM);const [choice,setChoice]=useState('');const [reasoning,setReasoning]=useState('');const [note,setNote]=useState('');const [comfort,setComfort]=useState(state.orientation?.comfort||'');const [confusion,setConfusion]=useState(state.orientation?.confusion||'');const [suspectedGaps,setSuspectedGaps]=useState(state.orientation?.suspectedGaps||'');const [graphs,setGraphs]=useState(state.orientation?.graphs||'no');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [settings,setSettings]=useState(false);const [mobileMenu,setMobileMenu]=useState(false);const [mode,setMode]=useState('guided');
 useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(state))},[state]);
 const history=state.history||[];const attempts=history.length;const right=history.filter(h=>h.isCorrect).length;const practiced=[...new Set(history.map(h=>h.skill).filter(Boolean))] as string[];
 async function requestAI({reset=false,repetition=false,sillyMistake=null}={}){
  if(!API_URL){setError('API endpoint missing. Configure VITE_API_URL in GitHub Actions or your local .env file.');return}
  setBusy(true);setError('');
  const previous=reset?null:state.currentQuestion;
  const answer=reset?null:(choice||null);
  const message=reset?theorem:(note||'');
  const data={theorem:reset?theorem:state.theorem||theorem,phase:reset?'Phase 0: orientation':state.phase||'Phase 0',mode:repetition?'repetition':mode,currentQuestion:previous,answer,reasoning:reset?'':reasoning,note:message,history:reset?[]:history.slice(-5),diagnosticsCount:reset?0:state.diagnosticsCount||0,orientation:reset?{comfort,confusion,suspectedGaps,graphs}:state.orientation,sillyMistake};
  try{
   const res=await fetch(`${API_URL}/tutor`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
   let output;try{output=await res.json()}catch{throw new Error(`HTTP ${res.status}: invalid API response`)}
   if(!res.ok)throw new Error(output.error||'Unable to reach tutor');
   const newHistory=reset?[]:answer&&previous?[...history,{question:previous.prompt,choice:answer,correctAnswer:previous.correctAnswer,reasoning,feedback:output.feedback,isCorrect:output.answerCorrect,skill:previous.skill}]:history;
   setState({theorem:reset?theorem:state.theorem||theorem,phase:output.phase||state.phase||'Phase 0',currentQuestion:output.awaitingSillyMistake?previous:output.nextQuestion,awaitingSillyMistake:output.awaitingSillyMistake,feedback:output.feedback,explanation:output.explanation,verdict:answer?output.answerCorrect:null,diagnosedSkill:output.diagnosedSkill,history:newHistory,mode:repetition?'repetition':mode,diagnosticsCount:output.diagnosticsCount??(state.diagnosticsCount||0),orientation:reset?{comfort,confusion,suspectedGaps,graphs}:state.orientation});
   setChoice('');setReasoning('');setNote('');
  }catch(e){setError(e.message||'Request failed')}finally{setBusy(false)}
 }
 function reset(){if(window.confirm('Reset this lesson and its local progress?')){setState({});setTheorem(DEFAULT_THEOREM);setChoice('');setReasoning('');setNote('');setError('')}}
 const active=state.currentQuestion;
 return <div className="app"><aside className={'sidebar '+(mobileMenu?'open':'')}><div className="brand"><div className="brandmark"><BookOpen size={22}/></div><div><div className="brandtitle">proofwise<span>.</span></div><div className="brandsub">V2 MASTERY STUDIO</div></div><button className="mobileClose" onClick={()=>setMobileMenu(false)}><X size={18}/></button></div>
 <div className="sidegroup"><div className="sidetitle">YOUR WORKSPACE</div><button className="sidenav active"><BookOpen size={18}/> Learning studio <span className="navdot"/></button><button className="sidenav" onClick={()=>document.getElementById('progress')?.scrollIntoView({behavior:'smooth'})}><BarChart3 size={18}/> Progress & insights</button><button className="sidenav" onClick={()=>setSettings(true)}><Settings2 size={18}/> Configuration</button></div>
 <div className="sidegroup"><div className="sidetitle">LEARNING JOURNEY</div><div className="phases">{phases.map(([id,label],i)=><div className={'phase '+(String(state.phase||'').includes(`Phase ${id}`)?'selected':'')} key={id}><div className="phase-index">{id}</div><span>{label}</span>{i<phases.length-1&&<div className="phaseconnector"/>}</div>)}</div></div>
 <div className="sidebarBottom"><div className="safeIcon"><ShieldCheck size={18}/></div><div><strong>Privacy-minded demo</strong><small>Progress stays in this browser. Your API key stays on Cloudflare.</small></div></div></aside>
 <main className="main"><header className="topbar"><button className="menuButton" onClick={()=>setMobileMenu(!mobileMenu)}><Menu size={20}/></button><div className="crumb">Learning Studio <ChevronRight size={14}/> <span>Real Analysis</span></div><div className="topright"><span className="liveDot"/> Gemini live tutoring <span className="topavatar">V2</span></div></header>
 <div className="content"><div className="eyebrow"><span className="eyedot"/> ADAPTIVE MATHEMATICS EDUCATION</div><h1>Understand the proof.<br/><span>Own the idea.</span></h1><p className="intro">Go beyond memorizing solutions. Build mathematical intuition, repair missing prerequisites, and reconstruct proofs — one deliberate step at a time.</p>
 <section className="lessonLayout"><div className="lessonMain"><div className="sectionlabel"><span className="sectionnum">01</span> CURRENT LEARNING OBJECTIVE</div><div className="theoremCard"><div className="cardTop"><div className="miniTag"><BookOpen size={14}/> SOURCE THEOREM</div><span className="chapter">Metric spaces</span></div><textarea className="theoremInput" rows={3} value={theorem} onChange={e=>setTheorem(e.target.value)} disabled={!!active||busy} aria-label="Theorem statement" maxLength={12000}/><label className="importFile">Import theorem, exercise, or proof text<input type="file" accept=".txt,.md,.tex,text/plain,text/markdown" disabled={!!active||busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>24000){setError('Imported text must be smaller than 24 KB.');e.target.value='';return}const text=await file.text();if(text.length>12000){setError('Imported text must be 12,000 characters or fewer.');e.target.value='';return}setTheorem(text);setError('');e.target.value=''}}/></label>{!active&&<div className="orientationFields"><div><label htmlFor="comfort">How comfortable are you with this problem?</label><select id="comfort" value={comfort} onChange={e=>setComfort(e.target.value)} disabled={busy}><option value="">Choose a level</option><option>New to it</option><option>Some pieces make sense</option><option>Mostly comfortable</option><option>Ready to prove it</option></select></div><div><label htmlFor="confusion">What feels confusing?</label><textarea id="confusion" rows={2} value={confusion} onChange={e=>setConfusion(e.target.value)} placeholder="Optional: name the part that feels unclear." disabled={busy}/></div><div><label htmlFor="gaps">Prerequisites you suspect may be weak</label><textarea id="gaps" rows={2} value={suspectedGaps} onChange={e=>setSuspectedGaps(e.target.value)} placeholder="Optional: e.g. subsequences or the Cauchy condition." disabled={busy}/></div><label className="graphChoice text-xs"><input type="checkbox" checked={graphs==='yes'} onChange={e=>setGraphs(e.target.checked?'yes':'no')} disabled={busy}/> Offer a diagram when it would clarify the mathematics</label></div>}<div className="theoremFooter"><span>Preserves your chosen theorem and notation</span>{!active&&<button className="button primary" disabled={busy||!theorem.trim()} onClick={()=>requestAI({reset:true})}>{busy?'Starting session…':'Start mastery session'} <ArrowRight size={17}/></button>}{active&&<button className="button secondary" onClick={reset}><RotateCcw size={14}/> New theorem</button>}</div></div>
 {active&&!state.awaitingSillyMistake&&<><div className="sectionlabel questionLabel"><span className="sectionnum">02</span> YOUR NEXT STEP <span className="questionCounter">{state.diagnosticsCount<10?`DIAGNOSTIC ${state.diagnosticsCount+1} OF 10`:`QUESTION ${attempts+1}`}</span></div><div className="questionCard"><div className="questionmeta"><span className="tag violet"><Brain size={14}/> {active.skill||'Proof reasoning'}</span><span className="mutedText">{active.difficulty||'Adaptive'}</span></div><div className="questionPrompt"><MathText text={active.prompt}/></div><div className="options" role="radiogroup" aria-label="Choose an answer">{active.options.map((opt,i)=><button key={i} className={'option '+(choice==='ABCDE'[i]?'chosen':'')} onClick={()=>setChoice('ABCDE'[i])} disabled={busy}><span className="optionLetter">{'ABCDE'[i]}</span><span className="optionText"><MathText text={opt.replace(/^[A-E][.)]\s*/, '')}/></span><span className="optionRadio"/></button>)}<button className={'option unknown '+(choice==='F'?'chosen':'')} onClick={()=>setChoice('F')} disabled={busy}><span className="optionLetter">F</span><span className="optionText">I don't know yet</span><span className="optionRadio"/></button></div><label className="fieldLabel" htmlFor="reason">Optional explanation / reasoning <span>OPTIONAL</span></label><textarea id="reason" className="reasonField" rows={3} value={reasoning} onChange={e=>setReasoning(e.target.value)} placeholder="What led you to that answer? Share your reasoning, doubts, or a question…" disabled={busy}/><div className="submitBar"><span>One step at a time. No rushing.</span><button className="button primary" disabled={busy||!choice} onClick={()=>requestAI()}>{busy?'Thinking…':'Submit answer'} <Send size={15}/></button></div></div></>}
 {state.feedback&&<div className={'feedbackCard '+(state.verdict===true?'positive':state.verdict===false?'negative':'neutral')}><div className="feedbackHeading">{state.verdict===true?<Check size={18}/>:state.verdict===false?<X size={18}/>:<MessageSquareText size={18}/>} {state.verdict===true?'You got it':state.verdict===false?'Not quite':'Tutor guidance'}</div><p><MathText text={state.feedback}/></p>{state.explanation&&<div className="explanation"><MathText text={state.explanation}/></div>}</div>}
 {state.awaitingSillyMistake&&<div className="inquiry sillyCheck"><span>Was this a silly mistake?</span><p>Use your judgment; your answer determines whether the tutor gives a same-level retry or repairs a concept gap.</p><div className="sillyActions"><button className="button secondary" disabled={busy} onClick={()=>requestAI({sillyMistake:true})}>Yes, a silly mistake</button><button className="button primary" disabled={busy} onClick={()=>requestAI({sillyMistake:false})}>No, I was unsure</button></div></div>}
 {active&&<div className="inquiry"><span>Need a different approach?</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="E.g. I’m lost — explain the purpose of this proof step." disabled={busy}/><button disabled={busy||!note.trim()} className="button secondary" onClick={()=>requestAI()}>Ask tutor <ArrowRight size={14}/></button><small>This requests clarification without marking a question attempt.</small></div>}
 {error&&<div className="error"><AlertCircle size={18}/> <span>{error}</span></div>}
 </div><div className="lessonAside" id="progress"><div className="statsCard"><div className="statHeading"><BarChart3 size={17}/> LEARNING SNAPSHOT</div><div className="statsgrid"><div><span className="bigStat">{attempts}</span><small>Attempts</small></div><div><span className="bigStat">{right}</span><small>Correct</small></div></div><div className="statsLine"><span>Practice accuracy</span><strong>{attempts?Math.round(right/attempts*100)+'%':'—'}</strong></div><div className="meter"><span style={{width:(attempts?right/attempts*100:0)+'%'}}/></div><p className="statfine">Accuracy is not mastery. Independent performance across varied problems matters more.</p></div><div className="insightCard"><div className="insightIcon"><Sparkles size={18}/></div><strong>Learn at your edge</strong><p>Your tutor adjusts the next step based on your answer and optional reasoning, prioritizing the original proof.</p>{state.diagnosedSkill&&<div className="focus"><span>CURRENT FOCUS</span><strong>{state.diagnosedSkill}</strong></div>}</div><div className="statsCard"><div className="statHeading"><Brain size={17}/> PRACTICED SKILLS</div>{practiced.length?practiced.map(s=><span className="skillpill" key={s}>{s}</span>):<p className="emptyStat">Complete your first question to begin collecting evidence.</p>}<button className="button repetition" disabled={!active||busy} onClick={()=>{setMode('repetition');requestAI({repetition:true})}}><RotateCcw size={15}/> Enter REPITITION mode</button></div></div></section><footer>Proofwise V2 · A research-inspired mastery learning prototype · AI output can be inaccurate; verify mathematical claims.</footer></div></main>
 {settings&&<div className="modalBg" onClick={()=>setSettings(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modalX" onClick={()=>setSettings(false)}><X size={18}/></button><h2>Connection settings</h2><p>The browser connects to a Cloudflare Worker. Your Gemini API key is never delivered to the browser.</p><div className="settingLine">Worker endpoint <code>{API_URL||'Not configured'}</code></div><div className="settingLine">Learning data <code>Browser localStorage</code></div><button className="button secondary" onClick={reset}>Clear lesson data</button><p className="settingHelp">To configure the endpoint, set <code>VITE_API_URL</code> in your local <code>.env</code> or GitHub repository Actions variable.</p></div></div>}
 </div>}

createRoot(document.getElementById('root')).render(<App/>);
